### ISSUE TITLE
As a farmer I want to store my data and not lose it

### ISSUE THREAD

**Issue by Joao-M-Almeida** [lidiamcfreitas/freyr#2]
Possibilities:
- CSV file;
- DB:
  - Postgres
  - SQLlite
  - DB specific for time series data

The permanent storage might be RPi specific, but then would need to be sent to a more secure and robust location. With deletion of data on RPi (specially images)

**Comment by lidiamcfreitas** [comment]
- [x] Store data in CSV file in Raspberry Pi where each day is a different logfile
- [x] Test this for a week

**Comment by lidiamcfreitas** [comment]
The data is being permanently stored for the sensors in CSV format on the RPi. The communication between the RPi and the server is not required for the MVP and will be addressed in issue #14 .
