### ISSUE TITLE
As a farmer I want to be able to access a website where I can see the information of my farm

### ISSUE THREAD

**Issue by lidiamcfreitas** [lidiamcfreitas/freyr#5]
Acceptance criteria:
- [x] Create a server for the API
- [x] Create a frontend server with the template for the base page
- [x] Front and backend must be working together even if the data is still stubs.
- [x] Testing of the connection must be done
- [x] Servers can run on desktop for now
- [x] Export conda environment file
- [x] Document process ro run the servers

**Comment by lidiamcfreitas** [comment]
Acceptance criteria:
- [ ] Create a server for the API
- [ ] Create a frontend server with the template for the base page
- [ ] Front and backend must be working together even if the data is still stubs.
- [ ] Testing of the connection must be done
- [ ] Servers can run on desktop for now

**Comment by Pedro-Roque** [comment]
@lidiamcfreitas iw this Django based?

**Comment by lidiamcfreitas** [comment]
Nope. Flask for the backend API and Vue for the frontend
